export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const GET_CURRENT_USER_ACTION = "GET_CURRENT_USER_ACTION";
export const LAY_LAI_MAT_KHAU_ACTION = "LAY_LAI_MAT_KHAU_ACTION";


export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_DETAIL = "GET_USER_DETAIL"

// Color
export const GET_COLOR_LIST = "GET_COLOR_LIST";
export const GET_COLOR_DETAIL = "GET_COLOR_DETAIL"
//Category
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_CATEGORY_DETAIL = "GET_ CATEGORY_DETAIL"
//Size
export const GET_SIZE_LIST = "GET_SIZE_LIST";
export const GET_SIZE_DETAIL = "GET_ SIZE_DETAIL"
// Order
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL"
export const GET_ORDER_DETAIL_BY_USER_ID = "GET_ORDER_DETAIL_BY_USER_ID"
// Payment
export const GET_PAYMENT_LIST = "GET_PAYMENT_LIST";
export const GET_PAYMENT_DETAIL = "GET_PAYMENT_DETAIL"
export const GET_PAYMENT_DETAIL_BY_USER_ID = "GET_PAYMENT_DETAIL_BY_USER_ID"
export const GET_MONTHLY_TOTAL_AMOUNT_OF_PAYMENT = "GET_MONTHLY_TOTAL_AMOUNT_OF_PAYMENT"
export const GET_MONTHLY_COUNT_ORDER = "GET_MONTHLY_COUNT_ORDER"


//Product
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_EIGHT_PRODUCTS = "GET_EIGHT_PRODUCTS";
export const GET_EIGHT_CHEAP_PRODUCTS = "GET_EIGHT_CHEAP_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_ PRODUCT_DETAIL"
export const GET_PRODUCT_DETAIL_FOR_USER = "GET_PRODUCT_DETAIL_FOR_USER"


export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

